language: php

php:
  - 7.0
  - 7.1

sudo: required

services:
  - docker

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-source --no-interaction

script:
  - ./vendor/bin/phing test

after_success:
  - bash <(curl -s https://codecov.io/bash)